# frozen_string_literal: true

# FlatPack keeps Tailwind class names in Ruby components. Dummy @source globs
# that assume vendor/bundle miss Bundler gem paths, so core PageNav can ship
# with no icon-only utilities. Resolve real gem roots at build time instead.
namespace :tailwindcss do
  desc "Write Bundler gem @source paths so Tailwind can scan FlatPack"
  task enhance_sources: :environment do
    css_path = Rails.root.join("app/assets/tailwind/gem_sources.css")
    lines = ["/* Generated by rake tailwindcss:enhance_sources. Do not edit. */"]

    gem_scan_roots = {
      "flat_pack" => ["app/components"],
      "recording_studio" => ["app/views"],
      "recording_studio_accessible" => ["app/views", "app/components"],
      "recording_studio_notifications" => ["app/views"],
      "recording_studio_notifications_push" => ["app/views"],
      "recording_studio_pwa" => ["app/views"],
      "recording_studio_root_switchable" => ["app/views"]
    }

    gem_scan_roots.each do |gem_name, relative_directories|
      spec = Gem.loaded_specs[gem_name]
      next unless spec

      relative_directories.each do |relative_directory|
        directory = File.join(spec.full_gem_path, relative_directory)
        next unless File.directory?(directory)

        glob = relative_directory.include?("components") ? "**/*.{rb,erb}" : "**/*.erb"
        lines << %(@source "#{directory}/#{glob}";)
      end
    end

    css_path.write("#{lines.join("\n")}\n")
  end
end

if Rake::Task.task_defined?("tailwindcss:build")
  Rake::Task["tailwindcss:build"].enhance(["tailwindcss:enhance_sources"])
end

if Rake::Task.task_defined?("tailwindcss:watch")
  Rake::Task["tailwindcss:watch"].enhance(["tailwindcss:enhance_sources"])
end
